---
# tasks file for haproxy
- name: Install haproxy
  apt:
   name: haproxy
   state: present
   update_cache: yes

- name: Copy haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy.cfg

- name: haproxy restart
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
