---
# tasks file for haproxy
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install haproxy
  apt:
   name: haproxy
   state: present
   update_cache: yes

- name: Copy haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: haproxy restart
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
