---
# tasks file for haproxy
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Disable UFW
  community.general.ufw:
    state: disabled

- name: Disable swap
  command: swapoff -a
  
- name: permanantly disable swap
  command:  sed -i '/swap/d' /etc/fstab

- name: Create /etc/sysctl.d/kubernetes.conf
  ansible.builtin.file:
    path: /etc/sysctl.d/kubernetes.conf
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Check for line net.bridge.bridge-nf-call-ip6tables
  shell: grep -c "^net.bridge.bridge-nf-call-ip6tables" /etc/sysctl.d/kubernetes.conf || true
  register: check_ip6tables

- name: Define net.bridge.bridge-nf-call-ip6tables if undefined
  lineinfile:
    state: present
    path: "/etc/sysctl.d/kubernetes.conf"
    line: "net.bridge.bridge-nf-call-ip6tables = 1"
  when: check_ip6tables.stdout == "0"
 
- name: Check for line net.bridge.bridge-nf-call-iptables
  shell: grep -c "^net.bridge.bridge-nf-call-iptables" /etc/sysctl.d/kubernetes.conf || true
  register: check_iptables

- name: Define net.bridge.bridge-nf-call-iptables if undefined
  lineinfile:
    state: present
    path: "/etc/sysctl.d/kubernetes.conf"
    line: "net.bridge.bridge-nf-call-iptables = 1"
  when: check_iptables.stdout == "0"

- name: Update sysctl settings for Kubernetes networking
  command: sysctl --system
 
- name: install docker engine pre-requisites
  apt:
   pkg:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common
   state: latest
   update_cache: true

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker
  apt:
   pkg:
    - docker.io
   state: present
   update_cache: true

- name: Configure additional engine options
  copy:
    content: "{{ docker_ce_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_ce_daemon_options is defined

- name: Add k8s apt repo key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present


- name: Add specified k8s repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install kubeadm, kubectl, kubelet
  apt:
   pkg:
    - kubeadm=1.21.0-00 
    - kubelet=1.21.0-00
    - kubectl=1.21.0-00
   update_cache: true

- name: install ipvsadm ipset xfsprogs lvm2 dmsetup
  apt:
   pkg:
    - ipvsadm 
    - ipset 
    - xfsprogs 
    - lvm2 
    - dmsetup
   update_cache: true

- name: Restart docker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes


- name: Restart kubelet service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
    enabled: yes
