---
- hosts: haproxy
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/keepalived
     - ../roles/haproxy

- hosts: k8s-master-primary,k8s-master-replicas,k8s-nodes
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/generic

- hosts: k8s-master-primary
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/bootstrap

- hosts: k8s-master-replicas
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/join-master

- hosts: k8s-nodes
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/join-worker
