---
- hosts: k8s-master, k8s-nodes
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/generic

- hosts: haproxy
  user: "{{ remote_user }}"
  become: yes
  become_user: root
  roles:
     - ../roles/haproxy
